runtime: nodejs16
env: standard

# Properly specify files to include
includes:
  - .env
  - deployments/**
  - artifacts/**

# Use basic scaling correctly
basic_scaling:
  max_instances: 2
  idle_timeout: 10m