runtime: nodejs20


# Scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080
  PRIVATE_KEY: "0xc9fc1cb318be162465ee2e222b94432bbbde124d161a4b058ea74f3ecd16a556"
  SEPOLIA_RPC_URL: "https://eth-sepolia.g.alchemy.com/v2/tCH4tNrSzoTvWI3mDLhDtEe0sGW-_Koe"
  MUMBAI_RPC_URL: "your_mumbai_rpc_url_here"
  ETHERSCAN_API_KEY: "your_etherscan_api_key_here"
  ADMIN_ADDRESS: "0x9a77A46f27ee0663fe44BC3b51dBba37092Cf9c0"
  MONGODB_URI: "mongodb+srv://harshitspotify123:lRbdISx8BHsr1h3u@myvote.tvf4crf.mongodb.net/myvote"
  ENCRYPTION_KEY: "45e12bcb6b83973ac8f3df07720a8b07"
 

# Instance class (adjust based on your needs)
instance_class: F2

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network configuration
network:
  forwarded_ports:
    - 8080