runtime: nodejs20
env: standard

# Environment variables
env_variables:
  NODE_ENV: 'production'
  PORT: '8080'

# Use automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 5
  max_concurrent_requests: 80

# Use the default instance class for now
instance_class: F2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

network:
  session_affinity: false