runtime: nodejs16
env: standard

# Use env_variables to inject environment variables
env_variables:
  NODE_ENV: 'production'

# Use basic scaling correctly
basic_scaling:
  max_instances: 2
  idle_timeout: 10m

# Properly list files to be included specifically
skip_files:
- ^node_modules$
- ^.git$
- ^.env$