runtime: nodejs16
env: standard

# Environment variables
env_variables:
  NODE_ENV: 'production'

# Use basic scaling
basic_scaling:
  max_instances: 2
  idle_timeout: 10m

# Files to skip
skip_files:
- ^node_modules$
- ^.git$
- ^.env$
- ^test$