steps:
  # Install dependencies with legacy peer deps to resolve ethers version conflict
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps']
    
  # Install missing Hardhat dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--save-dev', '@nomicfoundation/hardhat-ignition-ethers@^0.15.0', 'ts-node@>=8.0.0', 'typescript@>=4.5.0', '--legacy-peer-deps']
    
  # Verify deployment file exists and contains contract address (contract already deployed)
  - name: 'node:20'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        echo "Checking for deployments/sepolia.json..."
        if [ -f "deployments/sepolia.json" ]; then
          echo "✓ Found deployments/sepolia.json"
          echo "File contents:"
          cat deployments/sepolia.json
          echo ""
          echo "Contract address: $(node -e "
            try {
              const data = JSON.parse(require('fs').readFileSync('deployments/sepolia.json', 'utf8'));
              console.log(data.contractAddress || 'Contract address not found');
            } catch(e) {
              console.log('Error parsing JSON:', e.message);
              process.exit(1);
            }
          ")"
        else
          echo "✗ deployments/sepolia.json not found!"
          echo "Contract needs to be deployed first"
          exit 1
        fi
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Timeout for the build (adjust as needed)
timeout: '1200s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'