steps:
  # Install dependencies with legacy peer deps to resolve ethers version conflict
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps']
    
  # Verify deployment file exists and contains contract address
  - name: 'node:20'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        echo "Checking for deployments/sepolia.json..."
        if [ -f "deployments/sepolia.json" ]; then
          echo "✓ Found deployments/sepolia.json"
          echo "Contract address: $(node -e "console.log(JSON.parse(require('fs').readFileSync('deployments/sepolia.json', 'utf8')).contractAddress)")"
        else
          echo "✗ deployments/sepolia.json not found!"
          exit 1
        fi
    
  # Run tests (optional - uncomment if you have tests)
  # - name: 'node:20'
  #   entrypoint: 'npm'
  #   args: ['test']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Timeout for the build (adjust as needed)
timeout: '1200s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'