steps:
  # Install dependencies with legacy peer deps to resolve ethers version conflict
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps']
    
  # Install missing Hardhat toolbox dependency
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '@nomicfoundation/hardhat-toolbox', '--legacy-peer-deps']
    
  # Install missing Hardhat ignition dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--save-dev', '@nomicfoundation/hardhat-ignition@^0.15.11', '@nomicfoundation/ignition-core@^0.15.11', '--legacy-peer-deps']
    
  # Deploy contract to Sepolia network
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying contract to Sepolia network..."
        npx hardhat run scripts/deploy.js --network sepolia || echo "Contract deployment failed or may already be deployed"
        
  # Verify deployment file exists and contains contract address
  - name: 'node:20'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        echo "Checking for deployments/sepolia.json..."
        if [ -f "deployments/sepolia.json" ]; then
          echo "✓ Found deployments/sepolia.json"
          echo "File contents:"
          cat deployments/sepolia.json
          echo ""
          CONTRACT_ADDRESS=$$(node -e "
            try {
              const data = JSON.parse(require('fs').readFileSync('deployments/sepolia.json', 'utf8'));
              console.log(data.contractAddress || '');
            } catch(e) {
              console.log('');
              process.exit(1);
            }
          ")
          echo "Contract address: $$CONTRACT_ADDRESS"
          
          # Update app.yaml with the contract address
          if [ ! -z "$$CONTRACT_ADDRESS" ]; then
            echo "Updating app.yaml with CONTRACT_ADDRESS..."
            sed -i "/ENCRYPTION_KEY:/a\\  CONTRACT_ADDRESS: \"$$CONTRACT_ADDRESS\"" app.yaml
            echo "✓ app.yaml updated with CONTRACT_ADDRESS"
            echo "Updated app.yaml env_variables section:"
            grep -A 20 "env_variables:" app.yaml
          else
            echo "✗ Contract address is empty!"
            exit 1
          fi
        else
          echo "✗ deployments/sepolia.json not found!"
          echo "Creating deployments directory and checking if contract needs deployment..."
          mkdir -p deployments
          exit 1
        fi
    
  # Run tests (optional - uncomment if you have tests)
  # - name: 'node:20'
  #   entrypoint: 'npm'
  #   args: ['test']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Timeout for the build (adjust as needed)
timeout: '1200s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'