steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    id: 'install'
    args: ['install']
  
  # Enable required APIs
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'enable-apis'
    args: ['services', 'enable', 'appengine.googleapis.com']
    waitFor: ['-']  # Run in parallel with install
  
  # Compile contracts
  - name: 'gcr.io/cloud-builders/npm'
    id: 'compile'
    args: ['run', 'compile']
    waitFor: ['install']
  
  # Deploy contract to Sepolia
  - name: 'gcr.io/cloud-builders/npm'
    id: 'deploy-contract'
    args: ['run', 'deploy:sepolia']
    env:
      - 'PRIVATE_KEY=${_PRIVATE_KEY}'
      - 'SEPOLIA_RPC_URL=${_SEPOLIA_RPC_URL}'
    waitFor: ['compile']
  
  # Read contract address and create .env file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-env'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Reading contract address from sepolia.json"
        CONTRACT_ADDRESS=$$(cat deployments/sepolia.json | grep -o '"contractAddress": "[^"]*' | grep -o '[^"]*$')
        echo "Using contract address: $$CONTRACT_ADDRESS"
        echo "PORT=8080" > .env
        echo "CONTRACT_ADDRESS=$$CONTRACT_ADDRESS" >> .env
        echo "PRIVATE_KEY=${_PRIVATE_KEY}" >> .env
        echo "ADMIN_ADDRESS=${_ADMIN_ADDRESS}" >> .env
        echo "SEPOLIA_RPC_URL=${_SEPOLIA_RPC_URL}" >> .env
    waitFor: ['deploy-contract']
  
  # Check if App Engine exists and skip creation if necessary
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'verify-app'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Skip app creation as it requires owner permissions
        echo "Checking if App Engine is already set up"
        if gcloud app describe &>/dev/null; then
          echo "App Engine application already exists, proceeding with deployment"
        else
          echo "WARNING: App Engine application does not exist."
          echo "Please create an App Engine application manually in the Google Cloud Console:"
          echo "https://console.cloud.google.com/appengine/start?project=notional-yeti-461501-r9"
          echo "Select region 'us-central' and then rerun this build."
          exit 0  # Don't fail the build, just don't deploy
        fi
    waitFor: ['enable-apis']
  
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-app'
    args: ['app', 'deploy', '--quiet']
    waitFor: ['create-env', 'verify-app']

# Define substitution variables to be configured in the Cloud Build trigger
substitutions:
  _PRIVATE_KEY: '' # Set this in your Cloud Build trigger
  _ADMIN_ADDRESS: '' # Set this in your Cloud Build trigger
  _SEPOLIA_RPC_URL: '' # Set this in your Cloud Build trigger

# Set timeout for the entire build
timeout: '1800s' # 30 minutes

# Enable cloud logging for better debugging
options:
  logging: CLOUD_LOGGING_ONLY