steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    id: 'install-deps'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing production dependencies..."
        npm install express@^4.18.2 cors@^2.8.5 dotenv@^16.0.3 mongoose@^7.0.3 multer@^1.4.5-lts.1 ethers@^6.0.0 --production --legacy-peer-deps
        echo "Dependencies installed successfully"

  # Enable App Engine API
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'enable-apis'
    args: ['services', 'enable', 'appengine.googleapis.com']
    waitFor: ['-']

  # Prepare server.js
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'prepare-server'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Preparing server.js..."
        if [ -f "server.js" ]; then
          echo "✓ Found existing server.js file"
          sed -i 's/const PORT = process.env.PORT || 5000;/const PORT = process.env.PORT || 8080;/g' server.js
          sed -i "s/app.listen(PORT, () => {/app.listen(PORT, '0.0.0.0', () => {/g" server.js
          echo "✓ Updated server.js for App Engine"
        fi
        mkdir -p routes uploads public

  # Create route files
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-routes'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating route files..."
        
        # Create voters route only if it doesn't exist
        if [ ! -f "routes/voters.js" ]; then
          echo "Creating routes/voters.js..."
          cat > routes/voters.js << 'EOF'
        const express = require('express');
        const mongoose = require('mongoose');
        const router = express.Router();
        
        const voterSchema = new mongoose.Schema({
          name: String,
          email: String,
          address: String,
          verified: { type: Boolean, default: false },
          createdAt: { type: Date, default: Date.now }
        });
        
        const Voter = mongoose.models.Voter || mongoose.model('Voter', voterSchema);
        
        router.get('/', async (req, res) => {
          try {
            const voters = await Voter.find({});
            res.json({ 
              success: true, 
              message: 'Voters endpoint', 
              data: voters,
              count: voters.length,
              timestamp: new Date().toISOString()
            });
          } catch (error) {
            console.error('Error fetching voters:', error);
            res.status(500).json({
              success: false,
              message: 'Error fetching voters',
              error: error.message
            });
          }
        });
        
        module.exports = router;
        EOF
        else
          echo "✓ Found existing routes/voters.js, preserving it"
        fi
        
        # Create upload route only if it doesn't exist
        if [ ! -f "routes/upload.js" ]; then
          echo "Creating routes/upload.js..."
          cat > routes/upload.js << 'EOF'
        const express = require('express');
        const multer = require('multer');
        const router = express.Router();
        const upload = multer({ dest: 'uploads/' });
        
        router.post('/', upload.single('file'), (req, res) => {
          res.json({ success: true, message: 'File upload', file: req.file });
        });
        
        module.exports = router;
        EOF
        else
          echo "✓ Found existing routes/upload.js, preserving it"
        fi
        
        # Create health route only if it doesn't exist
        if [ ! -f "routes/health.js" ]; then
          echo "Creating routes/health.js..."
          cat > routes/health.js << 'EOF'
        const express = require('express');
        const router = express.Router();
        
        router.get('/', (req, res) => {
          res.json({ success: true, message: 'Health endpoint' });
        });
        
        module.exports = router;
        EOF
        else
          echo "✓ Found existing routes/health.js, preserving it"
        fi

  # Create blockchain and admin routes
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-more-routes'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create blockchain route only if it doesn't exist
        if [ ! -f "routes/blockchain.js" ]; then
          echo "Creating routes/blockchain.js..."
          cat > routes/blockchain.js << 'EOF'
        const express = require('express');
        const router = express.Router();
        
        router.get('/contract', (req, res) => {
          res.json({ 
            success: true,
            contractAddress: process.env.CONTRACT_ADDRESS || null,
            network: 'sepolia',
            rpcUrl: process.env.SEPOLIA_RPC_URL ? 'Configured' : 'Not configured'
          });
        });
        
        module.exports = router;
        EOF
        else
          echo "✓ Found existing routes/blockchain.js, preserving it"
        fi
        
        # Create admin route only if it doesn't exist
        if [ ! -f "routes/admin.js" ]; then
          echo "Creating routes/admin.js..."
          cat > routes/admin.js << 'EOF'
        const express = require('express');
        const router = express.Router();
        
        router.get('/dashboard', (req, res) => {
          res.json({ success: true, message: 'Admin dashboard' });
        });
        
        module.exports = router;
        EOF
        else
          echo "✓ Found existing routes/admin.js, preserving it"
        fi

  # Extract contract address from deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'extract-contract'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Extracting contract address from deployments/sepolia.json..."
        if [ -f "deployments/sepolia.json" ]; then
          CONTRACT_ADDR=$$(cat deployments/sepolia.json | grep -o '"contractAddress"[[:space:]]*:[[:space:]]*"[^"]*"' | grep -o '"[^"]*"$$' | tr -d '"')
          echo "Found contract address: $$CONTRACT_ADDR"
          echo "CONTRACT_ADDRESS=$$CONTRACT_ADDR" > contract.env
          echo "✓ Contract address extracted successfully"
        else
          echo "⚠️  deployments/sepolia.json not found, using empty contract address"
          echo "CONTRACT_ADDRESS=" > contract.env
        fi
    waitFor: ['prepare-server']

  # Verify files before deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'verify-files'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verifying all required files are present..."
        
        # Check for route files
        for route in voters upload blockchain admin health; do
          if [ -f "routes/$route.js" ]; then
            echo "✓ Found routes/$route.js"
          else
            echo "⚠️  Missing routes/$route.js"
          fi
        done
        
        # Check for controllers
        if [ -d "controllers" ]; then
          echo "✓ Found controllers directory"
          ls -la controllers/
        else
          echo "⚠️  Missing controllers directory"
        fi
        
        # Check for utils
        if [ -d "utils" ]; then
          echo "✓ Found utils directory"
          ls -la utils/
        else
          echo "⚠️  Missing utils directory"
        fi
        
        # Check for models
        if [ -d "models" ]; then
          echo "✓ Found models directory"
          ls -la models/
        else
          echo "⚠️  Missing models directory"
        fi
        
        echo "File verification complete"
    waitFor: ['extract-contract', 'create-routes', 'create-more-routes']

  # Create deployment files
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Read contract address from extracted file
        if [ -f "contract.env" ]; then
          source contract.env
          echo "Using contract address: $$CONTRACT_ADDRESS"
        else
          CONTRACT_ADDRESS=""
        fi
        
        # Create package.json
        cat > package.json << 'EOF'
        {
          "name": "myvote-backend",
          "version": "1.0.0",
          "main": "server.js",
          "scripts": { "start": "node server.js" },
          "dependencies": {
            "express": "^4.18.2",
            "cors": "^2.8.5",
            "dotenv": "^16.0.3",
            "mongoose": "^7.0.3",
            "multer": "^1.4.5-lts.1",
            "ethers": "^6.0.0"
          },
          "engines": { "node": "20.x", "npm": "10.x" }
        }
        EOF
        
        # Create app.yaml with dynamic contract address
        cat > app.yaml << EOF
        runtime: nodejs20
        env_variables:
          NODE_ENV: 'production'
          CONTRACT_ADDRESS: '$$CONTRACT_ADDRESS'
          SEPOLIA_RPC_URL: '${_SEPOLIA_RPC_URL}'
          ADMIN_ADDRESS: '${_ADMIN_ADDRESS}'
          MONGODB_URI: '${_MONGODB_URI}'
          ENCRYPTION_KEY: '${_ENCRYPTION_KEY}'
          PRIVATE_KEY: '${_PRIVATE_KEY}'
        automatic_scaling:
          min_instances: 1
          max_instances: 5
        readiness_check:
          path: "/health"
        liveness_check:
          path: "/health"
        EOF
        
        # Create .gcloudignore - only exclude unnecessary files
        cat > .gcloudignore << 'EOF'
        .git
        .github
        .vscode/
        test/
        *.md
        .env
        .env.*
        node_modules/.cache/
        npm-debug.log*
        yarn-debug.log*
        yarn-error.log*
        EOF
        
        echo "✓ Configuration files created with contract address: $$CONTRACT_ADDRESS"
    waitFor: ['verify-files']

  # Deploy to App Engine  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to App Engine..."
        rm -f package-lock.json
        gcloud app deploy --quiet --verbosity=info
    waitFor: ['create-config', 'enable-apis']

substitutions:
  _PRIVATE_KEY: '0xc9fc1cb318be162465ee2e222b94432bbbde124d161a4b058ea74f3ecd16a556'
  _ADMIN_ADDRESS: '0x9a77A46f27ee0663fe44BC3b51dBba37092Cf9c0'
  _SEPOLIA_RPC_URL: 'https://eth-sepolia.g.alchemy.com/v2/tCH4tNrSzoTvWI3mDLhDtEe0sGW-_Koe'
  _MONGODB_URI: 'mongodb+srv://harshitspotify123:lRbdISx8BHsr1h3u@myvote.tvf4crf.mongodb.net/myvote'
  _ENCRYPTION_KEY: ''

timeout: '900s'

options:
  logging: CLOUD_LOGGING_ONLY